### ISSUE TITLE
Bug in the code

### ISSUE THREAD

**Issue by trmittal24** [zhcHoward/Kmap#5]
Hi @zhcHoward , 

There seems to be a bug in the algorithm.  

I was trying with input

str_terms=` ["0001","0010","1001","1011","1100","1110","1111"]`
terms_not_care = []

The answer outputed by the code is:
`[11*0, 0010, *001]`

But the right answer is:
`[11*0, 0010, *001, 1*11]`

I was trying to debug the code, the issue seems to be with remove_repeated_sources which makes source list empty for everything except `[11*0, 0010, *001]`.  

Before remove_repeated_sources, we have the term 1*11 but it source list is made empty and then its removed by remove_redundant sources.

I did try to find a solution, but couldn't come across any. 

Glad to work it out together.

**Comment by zhcHoward** [comment]
Sorry for the delay, I didn't notice this issue until yesterday. I find out that this should be a bug within function `remove_repeated_sources()`. 
What `remove_repeated_sources()` does is that it removes unnecessary terms by comparing their sources. An unnecessary term means all of its sources are already included in other terms, so it should not appear in the final result. For example:
Let's say we have
```python
str_terms = ['010', '110', '111', '101']
terms_not_care = []
```
Its Karnaugh Map should be:
|C \ AB|00|01|11|10|
|-----|--|--|--|--|
|0||1|1||
|1|||1|1|

Before calling `remove_repeated_sources()`, min_terms is `['*10', '11*', '1*1']`. Because `11*`'s sources also appears in `*10` and `1*1`'s sources, `11*` will be removed in the end. So far, this algorithm works properly.

Your example creates a situation that I have not considered before. The Karnaugh Map for your example is:
|CD \ AB|00|01|11|10|
|-----|--|--|--|--|
|00|||1||
|01|1|||1|
|11|||1|1|
|10|1||1||

As you mentioned, `1*11` is removed after calling `remove_repeated_sources()`. This is because `1*11`'s sources also appears in `111*` and `10*1`'s sources. `1*11` is wrongly treated as an unnecessary term.

To bypass this bug, my suggestion would be after calling `remove_repeated_sources()`, finding out sources that does not appear in the result and do another round of simplification to those sources. For example, in your case,  `remove_repeated_sources()` returns `[11*0, 0010, *001]`. And if you look at their `source`, you will find out that none of them contains `1111` and `1011`. Now, you can treat `1111` and `1011` as `str_terms` and simplify them again, like
```python
minterms = Minterms([Term(t) for t in ['1111', '1011']])
minterms.simplify()
```
Finally, append the result to `[11*0, 0010, *001]`.

I am not sure wether this workaround would create any side effect. So strictly speaking, this is only a suggestion, not a solution. I hope this could give you some hints. For now, I am not going to fix this bug since I do not know how to. If you came up with a better solution, a PR is always welcome! Thank you.

**Comment by trmittal24** [comment]
Hi Zach, I have figured out the solution to the bug in the code. Upon deeper study, I found that your first step of simplification is similar to [Quine McCluskey Algorithm](https://en.wikipedia.org/wiki/Quine%E2%80%93McCluskey_algorithm) . And you find the essential prime implicants. Then we need the [Petrick's Method](https://en.wikipedia.org/wiki/Petrick%27s_method) to find other essential terms. I have put this in your code and I'll submit a PR.

Thanks for the response. :)
